### ISSUE TITLE
Iterators should not be reverse-iterable

### ISSUE THREAD

**Issue by domenic** [leebyron/ecmascript-reverse-iterator#2]
Given the answer to

> What happens if reverse() is called after an iterator has already been partially iterated?

I think there just should not be a [Symbol.reverseIterator] on any iterators like ArrayIterator etc. Instead, it should only exist on iterables.

**Comment by leebyron** [comment]
Perhaps so, that's certainly a viable alternative, but there are a few reasons why I think iterators (which are iterable) being reverse iterable is useful:
- API. This is a fairly minor point, but as currently proposed, the surface area of Array.prototype expands very little and `entries().reverse()` gets a reversed iterator of entries. Otherwise, we would need to introduce a set of parallel methods like `reverseEntries()`. The iterator instances hold useful contextual information that can be carried over to produce an equivalent iterator but in the opposite direction.
- Contextual info can also be the result of a higher order function such as `map` or `filter`. If `hof().reverse()` is equivalent to `reverse().hof()` then the mapped/filtered iterator can return a reversible iterator. That means more expressive power over building a reverse iterable.
- Similar to how any function or method which takes an Iterable can also take an Iterator, this would preserve the same for reversible. A good example of where this is useful is `reduceRight`.

You can see some of these examples in use in the work-in-progress https://github.com/leebyron/ecmascript-iterator-hof

## 

I'm also happy to discuss other options for what happens when you call reverse() on a partially iterated iterator.

Currently proposed throwing TypeError is to avoid a usage ambiguity, however there's nothing technically wrong with iterating the original a few times, then calling reverse on it. I just worry that the expected behavior might not match if used in that way.

Another thing that could be done is clean up or _IteratorClose_ the original when creating the reversed, to further enforce.

**Comment by domenic** [comment]
Hmm I think I see. OK, withdrawn.
